[graph]
all-features = true

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    #"RUSTSEC-0000-0000",
]

[licenses]
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
allow = [
    "AGPL-3.0",
    "Apache-2.0",
    "BSL-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "LicenseRef-UFL-1.0",
    "MIT",
    "MPL-2.0",
    "OFL-1.1",
    "Unicode-DFS-2016",
    "Zlib",
]
confidence-threshold = 0.97

[bans]
multiple-versions = "allow"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/Maximkaaa/galileo.git"]
